# Generated by Django 5.0.3 on 2024-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cartorder_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='title',
            field=models.CharField(default='Fresh Pear', max_length=100),
        ),
    ]
