# Generated by Django 5.0.3 on 2024-05-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cartorderitems_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='title',
        ),
    ]
